---

- hosts: watch.ocaml.org
  name: Install Tarsnap
  tasks:
  - name: Download Tarsnap's PGP public key
    apt_key:
      url: https://pkg.tarsnap.com/tarsnap-deb-packaging-key.asc
      keyring: /usr/share/keyrings/tarsnap-archive-keyring.gpg
      state: present
  - name: Add Tarsnap Repository
    apt_repository:
      repo:  "deb [signed-by=/usr/share/keyrings/tarsnap-archive-keyring.gpg] http://pkg.tarsnap.com/deb/{{ ansible_distribution_release|lower }} ./"
      filename: tarsnap
      state: present
      update_cache: yes
  - name: Install Tarsnap
    package:
      name: tarsnap
      state: present
  - name: Copy tarsnap key
    copy:
      content: "{{ tarsnap_key }}"
      dest: /root/tarsnap.key
      mode: 0600

- hosts: watch.ocaml.org
  name: Install Peer Tube
  tasks:
    - name: Set up SwarmKit
      docker_swarm:
        listen_addr: "127.0.0.1:2377"
        advertise_addr: "127.0.0.1:2377"
    - name: Query certbot volume
      docker_volume_info:
        name: certbot-conf
      register: result
    - name: Create certbot volume
      shell:
        cmd: docker volume create certbot-conf
      when: not result.exists
    - name: Initialise a certbot certificate
      shell:
        cmd: docker run --rm --name certbot -p 80:80 -v "certbot-conf:/etc/letsencrypt" certbot/certbot certonly --standalone -d watch.ocaml.org --expand -n --agree-tos -m mark@tarides.com
      when: not result.exists
    - name: Download the nginx configuration file from the template
      shell:
        cmd: docker run --rm -v nginx-conf:/etc/nginx/conf.d bash wget https://raw.githubusercontent.com/Chocobozzz/PeerTube/master/support/nginx/peertube -O /etc/nginx/conf.d/peertube.template
    - name: Copy environment
      copy:
        content: "{{ watch_env }}"
        dest: /root/.env
        mode: 0600
    - name: install docker-prune script
      copy:
        src: cron-scripts/docker-prune
        dest: /etc/cron.weekly/docker-prune
    - name: set up deployer stack
      docker_stack:
        name: infra
        prune: yes
        compose:
          - version: "3.3"
            services:
              webserver:
                image: chocobozzz/peertube-webserver:latest
                env_file:
                  - /root/.env
                deploy:
                  mode: global
                ports:
                 - target: 80
                   published: 80
                   protocol: tcp
                   mode: host
                 - target: 443
                   published: 443
                   protocol: tcp
                   mode: host
                volumes:
                  - nginx-conf:/etc/nginx/conf.d
                  - peertube-assets:/var/www/peertube/peertube-latest/client/dist:ro
                  - peertube-data:/var/www/peertube/storage
                  - certbot-www:/var/www/certbot
                  - certbot-conf:/etc/letsencrypt
                depends_on:
                  - peertube
                restart: "always"
              certbot:
                container_name: certbot
                image: certbot/certbot
                volumes:
                  - certbot-conf:/etc/letsencrypt
                  - certbot-www:/var/www/certbot
                restart: unless-stopped
                entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;"
                depends_on:
                  - webserver
              peertube:
                image: chocobozzz/peertube:production-bullseye
                # Use a static IP for this container because nginx does not handle proxy host change without reload
                # This container could be restarted on crash or until the postgresql database is ready for connection
                #networks:
                #  default:
                #    ipv4_address: 172.18.0.42
                env_file:
                  - /root/.env
                ports:
                 - "1935:1935" # If you don't want to use the live feature, you can comment this line
                volumes:
                  - peertube-assets:/app/client/dist
                  - peertube-data:/data
                  - peertube-conf:/config
                depends_on:
                  - postgres
                  - redis
                  - postfix
                restart: "always"
              postgres:
                env_file:
                  - /root/.env
                image: postgres:13-alpine
                volumes:
                  - postgres:/var/lib/postgresql/data
                restart: "always"
              redis:
                image: redis:6-alpine
                volumes:
                  - redis:/data
                restart: "always"
              postfix:
                image: mwader/postfix-relay
                env_file:
                  - /root/.env
                volumes:
                  - opendkim:/etc/opendkim/keys
                restart: "always"
            volumes:
              peertube-assets:
                external: true
              peertube-data:
                external: true
              peertube-conf:
                external: true
              nginx-conf:
                external: true
              certbot-conf:
                external: true
              certbot-www:
                external: true
              opendkim:
                external: true
              redis:
                external: true
              postgres:
                external: true

