- name: Check for Scaleway key deployment
  shell: scw-fetch-ssh-keys
  register: scw
  ignore_errors: true

- name: copy key
  ansible.posix.authorized_key:
    user: root
    state: present
    key: '{{ item }}'
  with_file:
    - id_rsa.pub
  when: scw.rc > 0

- name: copy key
  ansible.posix.authorized_key:
    user: root
    state: present
    key: '{{ item }}'
    path: '~/.ssh/instance_keys'
  with_file:
    - id_rsa.pub
  when: scw.rc == 0

- name: Import instance_keys to authorized_keys
  shell:
    cmd: scw-fetch-ssh-keys --upgrade
  when: scw.rc == 0
